version: '2.4'

services:
  db:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    command: -p 8461
    ports:
      - 8461:8461
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data:delegated
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      start_period: 10s
      timeout: 4s
      retries: 3

volumes:
  db-data:
